# Generated by Django 3.2.8 on 2021-10-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20211028_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=30, verbose_name='Брэнд')),
                ('model', models.CharField(db_index=True, max_length=30, verbose_name='Брэнд')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
                'ordering': ('model',),
            },
        ),
        migrations.CreateModel(
            name='ProductToPhone',
            fields=[
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='store.product', verbose_name='ID категории')),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.phone', verbose_name='ID телефона')),
            ],
        ),
    ]
