# Generated by Django 3.2.8 on 2021-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_phone_producttophone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttophone',
            options={'ordering': ('product_id',), 'verbose_name': 'Продукт-Телефон'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='img/category/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img/cases/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
