version: "3"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - web
    ports:
      - "80:80"
    volumes:
      - ./static/:/static

#Mine code
#version: "3"
#
#services:
#  postgresdb:
#    build:
#      context: ./docker/postgres
#      dockerfile: Dockerfile
#    environment:
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5432:5432"
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    volumes:
#      - ./:/usr/src/app
#    depends_on:
#      - postgresdb
#    ports:
#      - "8000:8000"

